#!/bin/bash
INSTALLPATH="/usr/lib/"
DEPLOYPATH="src/out/Debug"
if [[ "$1" == "install" ]]
  then
	INCLUDEPATH="/usr/include/gosui"
	cp $DEPLOYPATH/lib/* $INSTALLPATH
	mkdir -p $INCLUDEPATH
	cp src/app/*.h $INCLUDEPATH/
else
    ##THESE ARE THE MAIN COMMANDS TO RUN FOR BUILDING
    #modify skia_arch_width=32 to skia_arch_width=64 if your computer is 64-bit
	./src/build/gyp_using_skia.py -Dskia_arch_width=32
	ninja -C $DEPLOYPATH
    ##END
fi
